"""FreeCAD capability map -- a one-time, reproducible reverse-engineering of the
kernel's own foundation, owned by *our* system.

Rather than re-discovering "what does FreeCAD expose for X?" piecemeal every time
a new operator is wired, this module introspects the live kernel once and freezes
the result into a structured, queryable inventory (see
``cad_agent/capability_map.json``, regenerated by :func:`snapshot`). It captures,
for this pinned headless build:

* every importable kernel / workbench Python module and its public classes and
  module-level functions (the API surface an operator can call); and
* the OCCT BRep core -- the method surface of the topological shape classes
  (``Part.Shape`` / ``Solid`` / ``Face`` / ``Edge`` / ``Wire`` / ``Shell`` /
  ``Vertex`` / ``Compound``) -- which is the true geometric root everything else
  is built on.

:func:`coverage` then cross-references that surface against the operators we have
registered, so the *gap* between what the kernel offers and what we wrap is a
fact the system can report, not a guess. Reverse-engineer the foundation once;
build on the map thereafter.
"""
from __future__ import annotations

import importlib
import inspect
import json
import os
from typing import Any, Dict, List, Optional

# Modules probed for presence. Some are GUI-only (``*Gui``) or absent from a
# headless build; whichever import cleanly are recorded. Keeping the probe list
# explicit (rather than walking every importable name) keeps the snapshot stable
# and intentional.
PROBE_MODULES: List[str] = [
    "Part", "PartDesign", "Mesh", "MeshPart", "Sketcher", "Draft", "TechDraw",
    "Fem", "Path", "Points", "ReverseEngineering", "Surface", "Import",
    "importDXF", "BOPTools", "Arch", "Material", "Spreadsheet", "Measure",
    "DraftGeomUtils", "WorkingPlane",
]

# The topological core of the OCCT kernel: every richer feature ultimately
# produces / consumes one of these shape types, so their method surface is the
# foundation worth freezing in full.
SHAPE_CLASSES: List[str] = [
    "Shape", "Solid", "Shell", "Face", "Wire", "Edge", "Vertex", "Compound",
    "CompSolid",
]

# Operator-prefix -> the kernel module(s) that domain is built on. Used by
# :func:`coverage` to map our registry onto the kernel surface. ``None`` marks a
# domain with no direct kernel module (our own orchestration / app layer).
PREFIX_DOMAIN: Dict[str, Optional[str]] = {
    "solid": "Part", "analyze": "Part", "param": "PartDesign", "ss": "Sketcher",
    "mesh": "Mesh", "surface": "Surface", "points": "Points", "draft": "Draft",
    "draw": "TechDraw", "fem": "Fem", "path": "Path", "asm": None,
    "resource": None, "doc": None, "view": None, "out": None,
}

_MAP_PATH = os.path.join(os.path.dirname(__file__), "capability_map.json")


def _public(obj: Any) -> List[str]:
    return [a for a in dir(obj) if not a.startswith("_")]


def _module_surface(mod: Any) -> Dict[str, List[str]]:
    classes, functions = [], []
    for a in _public(mod):
        try:
            member = getattr(mod, a)
        except Exception:
            continue
        if inspect.isclass(member):
            classes.append(a)
        elif callable(member):
            functions.append(a)
    return {"classes": sorted(classes), "functions": sorted(functions)}


def scan() -> Dict[str, Any]:
    """Introspect the live kernel into a structured capability map. Requires a
    FreeCAD-enabled interpreter (``freecadcmd``); raises ``ImportError`` if the
    kernel is unavailable so callers fail loudly rather than silently empty."""
    import FreeCAD  # noqa: F401  -- fail loudly if no kernel

    modules: Dict[str, Dict[str, List[str]]] = {}
    for name in PROBE_MODULES:
        try:
            mod = importlib.import_module(name)
        except Exception:
            continue
        modules[name] = _module_surface(mod)

    shape_api: Dict[str, List[str]] = {}
    try:
        import Part
        for cls in SHAPE_CLASSES:
            obj = getattr(Part, cls, None)
            if obj is not None:
                shape_api[cls] = sorted(_public(obj))
    except Exception:
        pass

    n_classes = sum(len(m["classes"]) for m in modules.values())
    n_functions = sum(len(m["functions"]) for m in modules.values())
    return {
        "freecad_version": ".".join(str(x) for x in FreeCAD.Version()[:3]),
        "modules": modules,
        "shape_api": shape_api,
        "totals": {"modules": len(modules), "classes": n_classes,
                   "functions": n_functions,
                   "shape_methods": sum(len(v) for v in shape_api.values())},
    }


def coverage(registry_names: List[str]) -> Dict[str, Any]:
    """Cross-reference registered operators against the kernel module surface.

    Returns, per kernel module, how many operators wrap that domain, plus the
    modules that no operator touches yet (the honest gap) -- so "what is left to
    integrate" is a computed fact, not a hunch."""
    by_domain: Dict[str, int] = {}
    unknown_prefix: List[str] = []
    for full in registry_names:
        prefix = full.split(".", 1)[0]
        if prefix not in PREFIX_DOMAIN:
            unknown_prefix.append(full)
            continue
        dom = PREFIX_DOMAIN[prefix]
        key = dom if dom else "(app:%s)" % prefix
        by_domain[key] = by_domain.get(key, 0) + 1
    covered_modules = {d for d in by_domain if not d.startswith("(app:")}
    uncovered = sorted(m for m in PROBE_MODULES if m not in covered_modules)
    return {
        "operators": len(registry_names),
        "by_domain": dict(sorted(by_domain.items())),
        "covered_modules": sorted(covered_modules),
        "uncovered_modules": uncovered,
        "unknown_prefix": sorted(unknown_prefix),
    }


def load_map() -> Dict[str, Any]:
    """Load the frozen capability map committed to the repo."""
    with open(_MAP_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def snapshot(path: str = _MAP_PATH) -> Dict[str, Any]:
    """Regenerate the frozen map from a live scan and write it to ``path``.
    Run under ``freecadcmd`` whenever the pinned FreeCAD build changes."""
    data = scan()
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1, sort_keys=True)
        fh.write("\n")
    return data


if __name__ == "__main__":
    d = snapshot()
    print("capability map: %(modules)d modules, %(classes)d classes, "
          "%(functions)d functions, %(shape_methods)d shape methods"
          % d["totals"])
