"""FreeCAD capability map -- a one-time, reproducible reverse-engineering of the
kernel's own foundation, owned by *our* system.

Rather than re-discovering "what does FreeCAD expose for X?" piecemeal every time
a new operator is wired, this module introspects the live kernel once and freezes
the result into a structured, queryable inventory (see
``cad_agent/capability_map.json``, regenerated by :func:`snapshot`). It captures,
for this pinned headless build:

* every importable kernel / workbench Python module and its public classes and
  module-level functions (the API surface an operator can call); and
* the OCCT BRep core -- the method surface of the topological shape classes
  (``Part.Shape`` / ``Solid`` / ``Face`` / ``Edge`` / ``Wire`` / ``Shell`` /
  ``Vertex`` / ``Compound``) -- which is the true geometric root everything else
  is built on.

:func:`coverage` then cross-references that surface against the operators we have
registered, so the *gap* between what the kernel offers and what we wrap is a
fact the system can report, not a guess. Reverse-engineer the foundation once;
build on the map thereafter.
"""
from __future__ import annotations

import glob
import importlib
import inspect
import io
import json
import os
import re
import token as _tok
import tokenize
from typing import Any, Dict, List, Optional

# Modules probed for presence. Some are GUI-only (``*Gui``) or absent from a
# headless build; whichever import cleanly are recorded. Keeping the probe list
# explicit (rather than walking every importable name) keeps the snapshot stable
# and intentional.
PROBE_MODULES: List[str] = [
    "Part", "PartDesign", "Mesh", "MeshPart", "Sketcher", "Draft", "TechDraw",
    "Fem", "Path", "Points", "ReverseEngineering", "Surface", "Import",
    "importDXF", "BOPTools", "Arch", "Material", "Spreadsheet", "Measure",
    "DraftGeomUtils", "WorkingPlane",
]

# The topological core of the OCCT kernel: every richer feature ultimately
# produces / consumes one of these shape types, so their method surface is the
# foundation worth freezing in full.
SHAPE_CLASSES: List[str] = [
    "Shape", "Solid", "Shell", "Face", "Wire", "Edge", "Vertex", "Compound",
    "CompSolid",
]

# Operator-prefix -> the kernel module(s) that domain is built on. Used by
# :func:`coverage` to roll the registry up by domain. ``None`` marks a domain
# with no direct kernel module (our own orchestration / app layer).
PREFIX_DOMAIN: Dict[str, Optional[str]] = {
    "solid": "Part", "analyze": "Part", "param": "PartDesign", "ss": "Sketcher",
    "mesh": "Mesh", "surface": "Surface", "points": "Points", "draft": "Draft",
    "draw": "TechDraw", "fem": "Fem", "path": "Path", "asm": None,
    "resource": None, "doc": None, "view": None, "out": None,
    "reflect": None, "gui": None, "bim": "Arch", "wire": "DraftGeomUtils",
    "measure": "Measure", "bop": "BOPTools",
}

# A kernel module is rarely used under its own bare name: PartDesign is reached
# through ``"PartDesign::Body"`` TypeId strings, Fem through ``ObjectsFem`` /
# ``femtools`` / ``femmesh`` helpers, etc. Module -> the tokens whose presence in
# source means "this domain is genuinely wired", so usage is attributed by what
# the code *actually* calls rather than guessed from an operator's name.
MODULE_ALIASES: Dict[str, List[str]] = {
    "PartDesign": ["PartDesign"],
    "Fem": ["Fem", "ObjectsFem", "femtools", "femmesh"],
    "Path": ["Path"],
}

_MAP_PATH = os.path.join(os.path.dirname(__file__), "capability_map.json")


def _public(obj: Any) -> List[str]:
    return [a for a in dir(obj) if not a.startswith("_")]


def _module_surface(mod: Any) -> Dict[str, List[str]]:
    classes, functions = [], []
    for a in _public(mod):
        try:
            member = getattr(mod, a)
        except Exception:
            continue
        if inspect.isclass(member):
            classes.append(a)
        elif callable(member):
            functions.append(a)
    return {"classes": sorted(classes), "functions": sorted(functions)}


def scan() -> Dict[str, Any]:
    """Introspect the live kernel into a structured capability map. Requires a
    FreeCAD-enabled interpreter (``freecadcmd``); raises ``ImportError`` if the
    kernel is unavailable so callers fail loudly rather than silently empty."""
    import FreeCAD  # noqa: F401  -- fail loudly if no kernel

    modules: Dict[str, Dict[str, List[str]]] = {}
    for name in PROBE_MODULES:
        try:
            mod = importlib.import_module(name)
        except Exception:
            continue
        modules[name] = _module_surface(mod)

    shape_api: Dict[str, List[str]] = {}
    try:
        import Part
        for cls in SHAPE_CLASSES:
            obj = getattr(Part, cls, None)
            if obj is not None:
                shape_api[cls] = sorted(_public(obj))
    except Exception:
        pass

    n_classes = sum(len(m["classes"]) for m in modules.values())
    n_functions = sum(len(m["functions"]) for m in modules.values())
    return {
        "freecad_version": ".".join(str(x) for x in FreeCAD.Version()[:3]),
        "modules": modules,
        "shape_api": shape_api,
        "totals": {"modules": len(modules), "classes": n_classes,
                   "functions": n_functions,
                   "shape_methods": sum(len(v) for v in shape_api.values())},
    }


_BACKENDS_DIR = os.path.join(os.path.dirname(__file__), "backends")


_TYPEID_RE = re.compile(r"(?<![.\w])(\w+)::")


def _file_refs(src: str) -> set:
    """Names a single source file genuinely references as kernel modules.

    Works on the token stream so prose can't masquerade as code: a name counts
    when it is an ``import`` target or an attribute base ``Name.`` that is *not*
    itself an attribute (so ``f.Surface`` -- the Face's surface attribute --
    does not count as the ``Surface`` workbench), plus any ``Name::`` TypeId
    prefix found inside string literals (``"PartDesign::Body"``)."""
    refs: set = set()
    try:
        toks = list(tokenize.generate_tokens(io.StringIO(src).readline))
    except (tokenize.TokenError, IndentationError):
        return refs
    sig = [t for t in toks if t.type not in (_tok.COMMENT, _tok.NL, _tok.NEWLINE,
                                              _tok.INDENT, _tok.DEDENT)]
    for i, t in enumerate(sig):
        if t.type == _tok.STRING:
            refs.update(_TYPEID_RE.findall(t.string))
            continue
        if t.type != _tok.NAME:
            continue
        prev = sig[i - 1] if i > 0 else None
        nxt = sig[i + 1] if i + 1 < len(sig) else None
        preceded_by_dot = prev is not None and prev.type == _tok.OP \
            and prev.string == "."
        if prev is not None and prev.type == _tok.NAME \
                and prev.string in ("import", "from"):
            refs.add(t.string)                       # import target
        elif nxt is not None and nxt.type == _tok.OP and nxt.string == "." \
                and not preceded_by_dot:
            refs.add(t.string)                       # attribute base Name.
    return refs


def used_modules(source_root: str = _BACKENDS_DIR) -> Dict[str, List[str]]:
    """Which kernel modules the backend source *actually* references, and where.

    A module counts as used when one of its tokens (see :data:`MODULE_ALIASES`)
    is imported, used as an attribute base in code, or appears as a ``Mod::``
    TypeId literal -- never merely mentioned in prose. So usage reflects what the
    code calls, not what an operator is named. Returns ``module -> sorted list of
    files`` for every referenced module."""
    files = sorted(glob.glob(os.path.join(source_root, "**", "*.py"),
                             recursive=True))
    per_file = {}
    for f in files:
        with open(f, encoding="utf-8") as fh:
            per_file[os.path.basename(f)] = _file_refs(fh.read())
    out: Dict[str, List[str]] = {}
    for mod in PROBE_MODULES:
        tokens = set(MODULE_ALIASES.get(mod, [mod]))
        hits = sorted(name for name, refs in per_file.items() if refs & tokens)
        if hits:
            out[mod] = hits
    return out


def coverage(registry_names: List[str],
             source_root: str = _BACKENDS_DIR) -> Dict[str, Any]:
    """Cross-reference registered operators *and* backend source against the
    kernel module surface.

    ``by_domain`` rolls the registry up by operator-name prefix (the operator
    view). ``covered_modules`` / ``uncovered_modules`` are derived from what the
    source genuinely references (see :func:`used_modules`) -- not from the name
    prefix, which mis-attributes (e.g. ``points.reverse`` actually drives the
    ``ReverseEngineering`` module). So "what is left to integrate" is a computed
    fact about the code, not a hunch from naming."""
    by_domain: Dict[str, int] = {}
    unknown_prefix: List[str] = []
    for full in registry_names:
        prefix = full.split(".", 1)[0]
        if prefix not in PREFIX_DOMAIN:
            unknown_prefix.append(full)
            continue
        dom = PREFIX_DOMAIN[prefix]
        key = dom if dom else "(app:%s)" % prefix
        by_domain[key] = by_domain.get(key, 0) + 1
    used = used_modules(source_root)
    uncovered = sorted(m for m in PROBE_MODULES if m not in used)
    return {
        "operators": len(registry_names),
        "by_domain": dict(sorted(by_domain.items())),
        "covered_modules": sorted(used),
        "module_usage": used,
        "uncovered_modules": uncovered,
        "unknown_prefix": sorted(unknown_prefix),
    }


def load_map() -> Dict[str, Any]:
    """Load the frozen capability map committed to the repo."""
    with open(_MAP_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def snapshot(path: str = _MAP_PATH) -> Dict[str, Any]:
    """Regenerate the frozen map from a live scan and write it to ``path``.
    Run under ``freecadcmd`` whenever the pinned FreeCAD build changes."""
    data = scan()
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(data, fh, indent=1, sort_keys=True)
        fh.write("\n")
    return data


if __name__ == "__main__":
    d = snapshot()
    print("capability map: %(modules)d modules, %(classes)d classes, "
          "%(functions)d functions, %(shape_methods)d shape methods"
          % d["totals"])
